apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.serviceName }}
  name: ${{ values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.serviceName }}
  template:
    metadata:
      labels:
        app: ${{ values.serviceName }}
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "opentelemetry/instrumentation"
    spec:
      containers:
      - image: ${{ values.serviceName }}:v1
        name: ${{ values.serviceName }}
        imagePullPolicy: Never
        ports:
        - containerPort: ${{ values.port }}
          name: http
        env:
        - name: OTEL_SERVICE_NAME
          value: "${{ values.serviceName }}"